dark_theme: true
autoload_model: false
max_new_tokens: 200
max_new_tokens_min: 1
max_new_tokens_max: 16384
auto_max_new_tokens: false
seed: -1
negative_prompt: ''
character: None
name1: User
name2: Assistant
context: This is a conversation with your Assistant. It is a computer program designed to help you with various tasks such as answering questions, providing recommendations, and helping with decision making. You can ask it anything you want and it will do its best to give you accurate and relevant information.
greeting: ''
turn_template: ''
custom_stopping_strings: ''
add_bos_token: true
ban_eos_token: false
skip_special_tokens: true
truncation_length: 2048
truncation_length_min: 0
truncation_length_max: 32768
mode: chat
start_with: ''
chat_style: TheEncrypted777
instruction_template: None
chat-instruct_command: |-
  Continue the chat dialogue below. Write a single reply for the character "<|character|>".

  <|prompt|>
default_extensions:
- gallery
preset: simple-1
prompt: QA
